/*
 * SuprSend API
 * SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BrandCreateOrUpdateRequestSocialLinks
 */
public class BrandCreateOrUpdateRequestSocialLinksTest {
    private final BrandCreateOrUpdateRequestSocialLinks model = new BrandCreateOrUpdateRequestSocialLinks();

    /**
     * Model tests for BrandCreateOrUpdateRequestSocialLinks
     */
    @Test
    public void testBrandCreateOrUpdateRequestSocialLinks() {
        // TODO: test BrandCreateOrUpdateRequestSocialLinks
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'facebook'
     */
    @Test
    public void facebookTest() {
        // TODO: test facebook
    }

    /**
     * Test the property 'linkedin'
     */
    @Test
    public void linkedinTest() {
        // TODO: test linkedin
    }

    /**
     * Test the property 'twitter'
     */
    @Test
    public void twitterTest() {
        // TODO: test twitter
    }

    /**
     * Test the property 'instagram'
     */
    @Test
    public void instagramTest() {
        // TODO: test instagram
    }

    /**
     * Test the property 'medium'
     */
    @Test
    public void mediumTest() {
        // TODO: test medium
    }

    /**
     * Test the property 'discord'
     */
    @Test
    public void discordTest() {
        // TODO: test discord
    }

    /**
     * Test the property 'telegram'
     */
    @Test
    public void telegramTest() {
        // TODO: test telegram
    }

    /**
     * Test the property 'youtube'
     */
    @Test
    public void youtubeTest() {
        // TODO: test youtube
    }

}
