/*
 * SuprSend API
 * SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BrandCreateOrUpdateRequestSocialLinks;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BrandCreateOrUpdateRequest
 */
public class BrandCreateOrUpdateRequestTest {
    private final BrandCreateOrUpdateRequest model = new BrandCreateOrUpdateRequest();

    /**
     * Model tests for BrandCreateOrUpdateRequest
     */
    @Test
    public void testBrandCreateOrUpdateRequest() {
        // TODO: test BrandCreateOrUpdateRequest
    }

    /**
     * Test the property 'brandName'
     */
    @Test
    public void brandNameTest() {
        // TODO: test brandName
    }

    /**
     * Test the property 'logo'
     */
    @Test
    public void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'primaryColor'
     */
    @Test
    public void primaryColorTest() {
        // TODO: test primaryColor
    }

    /**
     * Test the property 'secondaryColor'
     */
    @Test
    public void secondaryColorTest() {
        // TODO: test secondaryColor
    }

    /**
     * Test the property 'tertiaryColor'
     */
    @Test
    public void tertiaryColorTest() {
        // TODO: test tertiaryColor
    }

    /**
     * Test the property 'preferencePageUrl'
     */
    @Test
    public void preferencePageUrlTest() {
        // TODO: test preferencePageUrl
    }

    /**
     * Test the property 'socialLinks'
     */
    @Test
    public void socialLinksTest() {
        // TODO: test socialLinks
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

}
