/*
 * SuprSend API
 * SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TemplateGetContentChannelResponseVersionsInnerTemplatesInner;
import com.konfigthis.client.model.TemplateGetContentChannelResponseVersionsInnerUpdatedBy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TemplateGetContentChannelResponseVersionsInner
 */
public class TemplateGetContentChannelResponseVersionsInnerTest {
    private final TemplateGetContentChannelResponseVersionsInner model = new TemplateGetContentChannelResponseVersionsInner();

    /**
     * Model tests for TemplateGetContentChannelResponseVersionsInner
     */
    @Test
    public void testTemplateGetContentChannelResponseVersionsInner() {
        // TODO: test TemplateGetContentChannelResponseVersionsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'templates'
     */
    @Test
    public void templatesTest() {
        // TODO: test templates
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'versionTag'
     */
    @Test
    public void versionTagTest() {
        // TODO: test versionTag
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'updatedBy'
     */
    @Test
    public void updatedByTest() {
        // TODO: test updatedBy
    }

    /**
     * Test the property 'versionTagUser'
     */
    @Test
    public void versionTagUserTest() {
        // TODO: test versionTagUser
    }

    /**
     * Test the property 'publishedLanguages'
     */
    @Test
    public void publishedLanguagesTest() {
        // TODO: test publishedLanguages
    }

    /**
     * Test the property 'apparentPublishedLanguages'
     */
    @Test
    public void apparentPublishedLanguagesTest() {
        // TODO: test apparentPublishedLanguages
    }

}
