/*
 * SuprSend API
 * SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerLanguage
 */
public class TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerLanguageTest {
    private final TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerLanguage model = new TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerLanguage();

    /**
     * Model tests for TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerLanguage
     */
    @Test
    public void testTemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerLanguage() {
        // TODO: test TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerLanguage
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

}
