/*
 * SuprSend API
 * SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TemplateGetListResponseResultsInnerChannelsInner;
import com.konfigthis.client.model.TemplateGetListResponseResultsInnerDefaultLanguage;
import com.konfigthis.client.model.TemplateGetListResponseResultsInnerUpdatedBy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TemplateGetListResponseResultsInner
 */
public class TemplateGetListResponseResultsInnerTest {
    private final TemplateGetListResponseResultsInner model = new TemplateGetListResponseResultsInner();

    /**
     * Model tests for TemplateGetListResponseResultsInner
     */
    @Test
    public void testTemplateGetListResponseResultsInner() {
        // TODO: test TemplateGetListResponseResultsInner
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'defaultLanguage'
     */
    @Test
    public void defaultLanguageTest() {
        // TODO: test defaultLanguage
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'updatedBy'
     */
    @Test
    public void updatedByTest() {
        // TODO: test updatedBy
    }

    /**
     * Test the property 'lastTriggeredAt'
     */
    @Test
    public void lastTriggeredAtTest() {
        // TODO: test lastTriggeredAt
    }

    /**
     * Test the property 'isAutoTranslateEnabled'
     */
    @Test
    public void isAutoTranslateEnabledTest() {
        // TODO: test isAutoTranslateEnabled
    }

    /**
     * Test the property 'enabledLanguages'
     */
    @Test
    public void enabledLanguagesTest() {
        // TODO: test enabledLanguages
    }

    /**
     * Test the property 'channels'
     */
    @Test
    public void channelsTest() {
        // TODO: test channels
    }

}
