/*
 * SuprSend API
 * SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerApprovalCycle;
import com.konfigthis.client.model.TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent;
import com.konfigthis.client.model.TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerLanguage;
import com.konfigthis.client.model.TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerUpdatedBy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInner
 */
public class TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerTest {
    private final TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInner model = new TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInner();

    /**
     * Model tests for TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInner
     */
    @Test
    public void testTemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInner() {
        // TODO: test TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'isEnabled'
     */
    @Test
    public void isEnabledTest() {
        // TODO: test isEnabled
    }

    /**
     * Test the property 'approvalStatus'
     */
    @Test
    public void approvalStatusTest() {
        // TODO: test approvalStatus
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'updatedBy'
     */
    @Test
    public void updatedByTest() {
        // TODO: test updatedBy
    }

    /**
     * Test the property 'approvalCycle'
     */
    @Test
    public void approvalCycleTest() {
        // TODO: test approvalCycle
    }

    /**
     * Test the property 'isApprovalNeeded'
     */
    @Test
    public void isApprovalNeededTest() {
        // TODO: test isApprovalNeeded
    }

    /**
     * Test the property 'isClonedFromLastVersion'
     */
    @Test
    public void isClonedFromLastVersionTest() {
        // TODO: test isClonedFromLastVersion
    }

}
