/*
 * SuprSend API
 * SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
 */
public class TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContentTest {
    private final TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent model = new TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent();

    /**
     * Model tests for TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
     */
    @Test
    public void testTemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent() {
        // TODO: test TemplateGetDetailsResponseChannelsInnerVersionsInnerTemplatesInnerContent
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'header'
     */
    @Test
    public void headerTest() {
        // TODO: test header
    }

    /**
     * Test the property 'example'
     */
    @Test
    public void exampleTest() {
        // TODO: test example
    }

    /**
     * Test the property 'vendorSlug'
     */
    @Test
    public void vendorSlugTest() {
        // TODO: test vendorSlug
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'messageType'
     */
    @Test
    public void messageTypeTest() {
        // TODO: test messageType
    }

    /**
     * Test the property 'templateName'
     */
    @Test
    public void templateNameTest() {
        // TODO: test templateName
    }

    /**
     * Test the property 'enterpriseName'
     */
    @Test
    public void enterpriseNameTest() {
        // TODO: test enterpriseName
    }

    /**
     * Test the property 'handlebarsText'
     */
    @Test
    public void handlebarsTextTest() {
        // TODO: test handlebarsText
    }

    /**
     * Test the property 'vendorTemplateId'
     */
    @Test
    public void vendorTemplateIdTest() {
        // TODO: test vendorTemplateId
    }

    /**
     * Test the property 'xKonfigOriginalExample'
     */
    @Test
    public void xKonfigOriginalExampleTest() {
        // TODO: test xKonfigOriginalExample
    }

}
