/*
 * SuprSend API
 * SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TemplateGetDetailsResponseChannelsInnerChannel;
import com.konfigthis.client.model.TemplateGetDetailsResponseChannelsInnerVersionsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TemplateGetDetailsResponseChannelsInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TemplateGetDetailsResponseChannelsInner {
  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<Object> tags = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id = 0;

  public static final String SERIALIZED_NAME_CHANNEL = "channel";
  @SerializedName(SERIALIZED_NAME_CHANNEL)
  private TemplateGetDetailsResponseChannelsInnerChannel channel;

  public static final String SERIALIZED_NAME_IS_ACTIVE = "is_active";
  @SerializedName(SERIALIZED_NAME_IS_ACTIVE)
  private Boolean isActive = true;

  public static final String SERIALIZED_NAME_IS_ENABLED = "is_enabled";
  @SerializedName(SERIALIZED_NAME_IS_ENABLED)
  private Boolean isEnabled = true;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_DISABLED_LANGUAGES = "disabled_languages";
  @SerializedName(SERIALIZED_NAME_DISABLED_LANGUAGES)
  private List<Object> disabledLanguages = null;

  public static final String SERIALIZED_NAME_VERSIONS = "versions";
  @SerializedName(SERIALIZED_NAME_VERSIONS)
  private List<TemplateGetDetailsResponseChannelsInnerVersionsInner> versions = null;

  public TemplateGetDetailsResponseChannelsInner() {
  }

  public TemplateGetDetailsResponseChannelsInner tags(List<Object> tags) {
    
    
    
    
    this.tags = tags;
    return this;
  }

  public TemplateGetDetailsResponseChannelsInner addTagsItem(Object tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getTags() {
    return tags;
  }


  public void setTags(List<Object> tags) {
    
    
    
    this.tags = tags;
  }


  public TemplateGetDetailsResponseChannelsInner id(Integer id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3944", value = "")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    
    
    
    this.id = id;
  }


  public TemplateGetDetailsResponseChannelsInner channel(TemplateGetDetailsResponseChannelsInnerChannel channel) {
    
    
    
    
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateGetDetailsResponseChannelsInnerChannel getChannel() {
    return channel;
  }


  public void setChannel(TemplateGetDetailsResponseChannelsInnerChannel channel) {
    
    
    
    this.channel = channel;
  }


  public TemplateGetDetailsResponseChannelsInner isActive(Boolean isActive) {
    
    
    
    
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsActive() {
    return isActive;
  }


  public void setIsActive(Boolean isActive) {
    
    
    
    this.isActive = isActive;
  }


  public TemplateGetDetailsResponseChannelsInner isEnabled(Boolean isEnabled) {
    
    
    
    
    this.isEnabled = isEnabled;
    return this;
  }

   /**
   * Get isEnabled
   * @return isEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsEnabled() {
    return isEnabled;
  }


  public void setIsEnabled(Boolean isEnabled) {
    
    
    
    this.isEnabled = isEnabled;
  }


  public TemplateGetDetailsResponseChannelsInner createdAt(String createdAt) {
    
    
    
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2023-01-25T04:53:39.268299Z", value = "")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    
    
    
    this.createdAt = createdAt;
  }


  public TemplateGetDetailsResponseChannelsInner updatedAt(String updatedAt) {
    
    
    
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2023-01-25T04:53:39.404273Z", value = "")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    
    
    
    this.updatedAt = updatedAt;
  }


  public TemplateGetDetailsResponseChannelsInner disabledLanguages(List<Object> disabledLanguages) {
    
    
    
    
    this.disabledLanguages = disabledLanguages;
    return this;
  }

  public TemplateGetDetailsResponseChannelsInner addDisabledLanguagesItem(Object disabledLanguagesItem) {
    if (this.disabledLanguages == null) {
      this.disabledLanguages = new ArrayList<>();
    }
    this.disabledLanguages.add(disabledLanguagesItem);
    return this;
  }

   /**
   * Get disabledLanguages
   * @return disabledLanguages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getDisabledLanguages() {
    return disabledLanguages;
  }


  public void setDisabledLanguages(List<Object> disabledLanguages) {
    
    
    
    this.disabledLanguages = disabledLanguages;
  }


  public TemplateGetDetailsResponseChannelsInner versions(List<TemplateGetDetailsResponseChannelsInnerVersionsInner> versions) {
    
    
    
    
    this.versions = versions;
    return this;
  }

  public TemplateGetDetailsResponseChannelsInner addVersionsItem(TemplateGetDetailsResponseChannelsInnerVersionsInner versionsItem) {
    if (this.versions == null) {
      this.versions = new ArrayList<>();
    }
    this.versions.add(versionsItem);
    return this;
  }

   /**
   * Get versions
   * @return versions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<TemplateGetDetailsResponseChannelsInnerVersionsInner> getVersions() {
    return versions;
  }


  public void setVersions(List<TemplateGetDetailsResponseChannelsInnerVersionsInner> versions) {
    
    
    
    this.versions = versions;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TemplateGetDetailsResponseChannelsInner instance itself
   */
  public TemplateGetDetailsResponseChannelsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateGetDetailsResponseChannelsInner templateGetDetailsResponseChannelsInner = (TemplateGetDetailsResponseChannelsInner) o;
    return Objects.equals(this.tags, templateGetDetailsResponseChannelsInner.tags) &&
        Objects.equals(this.id, templateGetDetailsResponseChannelsInner.id) &&
        Objects.equals(this.channel, templateGetDetailsResponseChannelsInner.channel) &&
        Objects.equals(this.isActive, templateGetDetailsResponseChannelsInner.isActive) &&
        Objects.equals(this.isEnabled, templateGetDetailsResponseChannelsInner.isEnabled) &&
        Objects.equals(this.createdAt, templateGetDetailsResponseChannelsInner.createdAt) &&
        Objects.equals(this.updatedAt, templateGetDetailsResponseChannelsInner.updatedAt) &&
        Objects.equals(this.disabledLanguages, templateGetDetailsResponseChannelsInner.disabledLanguages) &&
        Objects.equals(this.versions, templateGetDetailsResponseChannelsInner.versions)&&
        Objects.equals(this.additionalProperties, templateGetDetailsResponseChannelsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tags, id, channel, isActive, isEnabled, createdAt, updatedAt, disabledLanguages, versions, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateGetDetailsResponseChannelsInner {\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    disabledLanguages: ").append(toIndentedString(disabledLanguages)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tags");
    openapiFields.add("id");
    openapiFields.add("channel");
    openapiFields.add("is_active");
    openapiFields.add("is_enabled");
    openapiFields.add("created_at");
    openapiFields.add("updated_at");
    openapiFields.add("disabled_languages");
    openapiFields.add("versions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TemplateGetDetailsResponseChannelsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TemplateGetDetailsResponseChannelsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateGetDetailsResponseChannelsInner is not found in the empty JSON string", TemplateGetDetailsResponseChannelsInner.openapiRequiredFields.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
      // validate the optional field `channel`
      if (jsonObj.get("channel") != null && !jsonObj.get("channel").isJsonNull()) {
        TemplateGetDetailsResponseChannelsInnerChannel.validateJsonObject(jsonObj.getAsJsonObject("channel"));
      }
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("updated_at") != null && !jsonObj.get("updated_at").isJsonNull()) && !jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("disabled_languages") != null && !jsonObj.get("disabled_languages").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `disabled_languages` to be an array in the JSON string but got `%s`", jsonObj.get("disabled_languages").toString()));
      }
      if (jsonObj.get("versions") != null && !jsonObj.get("versions").isJsonNull()) {
        JsonArray jsonArrayversions = jsonObj.getAsJsonArray("versions");
        if (jsonArrayversions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("versions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `versions` to be an array in the JSON string but got `%s`", jsonObj.get("versions").toString()));
          }

          // validate the optional field `versions` (array)
          for (int i = 0; i < jsonArrayversions.size(); i++) {
            TemplateGetDetailsResponseChannelsInnerVersionsInner.validateJsonObject(jsonArrayversions.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateGetDetailsResponseChannelsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateGetDetailsResponseChannelsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateGetDetailsResponseChannelsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateGetDetailsResponseChannelsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateGetDetailsResponseChannelsInner>() {
           @Override
           public void write(JsonWriter out, TemplateGetDetailsResponseChannelsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateGetDetailsResponseChannelsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TemplateGetDetailsResponseChannelsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TemplateGetDetailsResponseChannelsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TemplateGetDetailsResponseChannelsInner
  * @throws IOException if the JSON string is invalid with respect to TemplateGetDetailsResponseChannelsInner
  */
  public static TemplateGetDetailsResponseChannelsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateGetDetailsResponseChannelsInner.class);
  }

 /**
  * Convert an instance of TemplateGetDetailsResponseChannelsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

