/*
 * SuprSend API
 * SuprSend is a central communication stack for easily creating, managing and delivering notifications to your end users on multiple channels. Our single notification API has all the features set, which enables you to send notifications in a reliable and scalable manner and take care of end user experience, thereby eliminating the need to develop any notification service in-house for transactional/engagement notifications.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TemplateGetContentChannelResponseVersionsInnerTemplatesInnerContent;
import com.konfigthis.client.model.TemplateGetContentChannelResponseVersionsInnerTemplatesInnerLanguage;
import com.konfigthis.client.model.TemplateGetContentChannelResponseVersionsInnerTemplatesInnerUpdatedBy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TemplateGetContentChannelResponseVersionsInnerTemplatesInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TemplateGetContentChannelResponseVersionsInnerTemplatesInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id = 0;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private TemplateGetContentChannelResponseVersionsInnerTemplatesInnerLanguage language;

  public static final String SERIALIZED_NAME_IS_ENABLED = "is_enabled";
  @SerializedName(SERIALIZED_NAME_IS_ENABLED)
  private Boolean isEnabled = true;

  public static final String SERIALIZED_NAME_APPROVAL_STATUS = "approval_status";
  @SerializedName(SERIALIZED_NAME_APPROVAL_STATUS)
  private String approvalStatus;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private TemplateGetContentChannelResponseVersionsInnerTemplatesInnerContent content;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_UPDATED_BY = "updated_by";
  @SerializedName(SERIALIZED_NAME_UPDATED_BY)
  private TemplateGetContentChannelResponseVersionsInnerTemplatesInnerUpdatedBy updatedBy;

  public static final String SERIALIZED_NAME_APPROVAL_CYCLE = "approval_cycle";
  @SerializedName(SERIALIZED_NAME_APPROVAL_CYCLE)
  private Object approvalCycle = null;

  public static final String SERIALIZED_NAME_IS_APPROVAL_NEEDED = "is_approval_needed";
  @SerializedName(SERIALIZED_NAME_IS_APPROVAL_NEEDED)
  private Boolean isApprovalNeeded = true;

  public static final String SERIALIZED_NAME_IS_CLONED_FROM_LAST_VERSION = "is_cloned_from_last_version";
  @SerializedName(SERIALIZED_NAME_IS_CLONED_FROM_LAST_VERSION)
  private Boolean isClonedFromLastVersion = true;

  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner() {
  }

  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner id(Integer id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "11876", value = "")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    
    
    
    this.id = id;
  }


  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner language(TemplateGetContentChannelResponseVersionsInnerTemplatesInnerLanguage language) {
    
    
    
    
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateGetContentChannelResponseVersionsInnerTemplatesInnerLanguage getLanguage() {
    return language;
  }


  public void setLanguage(TemplateGetContentChannelResponseVersionsInnerTemplatesInnerLanguage language) {
    
    
    
    this.language = language;
  }


  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner isEnabled(Boolean isEnabled) {
    
    
    
    
    this.isEnabled = isEnabled;
    return this;
  }

   /**
   * Get isEnabled
   * @return isEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsEnabled() {
    return isEnabled;
  }


  public void setIsEnabled(Boolean isEnabled) {
    
    
    
    this.isEnabled = isEnabled;
  }


  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner approvalStatus(String approvalStatus) {
    
    
    
    
    this.approvalStatus = approvalStatus;
    return this;
  }

   /**
   * Get approvalStatus
   * @return approvalStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "auto_approved", value = "")

  public String getApprovalStatus() {
    return approvalStatus;
  }


  public void setApprovalStatus(String approvalStatus) {
    
    
    
    this.approvalStatus = approvalStatus;
  }


  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner content(TemplateGetContentChannelResponseVersionsInnerTemplatesInnerContent content) {
    
    
    
    
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateGetContentChannelResponseVersionsInnerTemplatesInnerContent getContent() {
    return content;
  }


  public void setContent(TemplateGetContentChannelResponseVersionsInnerTemplatesInnerContent content) {
    
    
    
    this.content = content;
  }


  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner createdAt(String createdAt) {
    
    
    
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2023-01-25T04:53:40.035836Z", value = "")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    
    
    
    this.createdAt = createdAt;
  }


  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner updatedAt(String updatedAt) {
    
    
    
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2023-01-25T04:53:40.069659Z", value = "")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    
    
    
    this.updatedAt = updatedAt;
  }


  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner updatedBy(TemplateGetContentChannelResponseVersionsInnerTemplatesInnerUpdatedBy updatedBy) {
    
    
    
    
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Get updatedBy
   * @return updatedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateGetContentChannelResponseVersionsInnerTemplatesInnerUpdatedBy getUpdatedBy() {
    return updatedBy;
  }


  public void setUpdatedBy(TemplateGetContentChannelResponseVersionsInnerTemplatesInnerUpdatedBy updatedBy) {
    
    
    
    this.updatedBy = updatedBy;
  }


  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner approvalCycle(Object approvalCycle) {
    
    
    
    
    this.approvalCycle = approvalCycle;
    return this;
  }

   /**
   * Get approvalCycle
   * @return approvalCycle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getApprovalCycle() {
    return approvalCycle;
  }


  public void setApprovalCycle(Object approvalCycle) {
    
    
    
    this.approvalCycle = approvalCycle;
  }


  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner isApprovalNeeded(Boolean isApprovalNeeded) {
    
    
    
    
    this.isApprovalNeeded = isApprovalNeeded;
    return this;
  }

   /**
   * Get isApprovalNeeded
   * @return isApprovalNeeded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getIsApprovalNeeded() {
    return isApprovalNeeded;
  }


  public void setIsApprovalNeeded(Boolean isApprovalNeeded) {
    
    
    
    this.isApprovalNeeded = isApprovalNeeded;
  }


  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner isClonedFromLastVersion(Boolean isClonedFromLastVersion) {
    
    
    
    
    this.isClonedFromLastVersion = isClonedFromLastVersion;
    return this;
  }

   /**
   * Get isClonedFromLastVersion
   * @return isClonedFromLastVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getIsClonedFromLastVersion() {
    return isClonedFromLastVersion;
  }


  public void setIsClonedFromLastVersion(Boolean isClonedFromLastVersion) {
    
    
    
    this.isClonedFromLastVersion = isClonedFromLastVersion;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TemplateGetContentChannelResponseVersionsInnerTemplatesInner instance itself
   */
  public TemplateGetContentChannelResponseVersionsInnerTemplatesInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateGetContentChannelResponseVersionsInnerTemplatesInner templateGetContentChannelResponseVersionsInnerTemplatesInner = (TemplateGetContentChannelResponseVersionsInnerTemplatesInner) o;
    return Objects.equals(this.id, templateGetContentChannelResponseVersionsInnerTemplatesInner.id) &&
        Objects.equals(this.language, templateGetContentChannelResponseVersionsInnerTemplatesInner.language) &&
        Objects.equals(this.isEnabled, templateGetContentChannelResponseVersionsInnerTemplatesInner.isEnabled) &&
        Objects.equals(this.approvalStatus, templateGetContentChannelResponseVersionsInnerTemplatesInner.approvalStatus) &&
        Objects.equals(this.content, templateGetContentChannelResponseVersionsInnerTemplatesInner.content) &&
        Objects.equals(this.createdAt, templateGetContentChannelResponseVersionsInnerTemplatesInner.createdAt) &&
        Objects.equals(this.updatedAt, templateGetContentChannelResponseVersionsInnerTemplatesInner.updatedAt) &&
        Objects.equals(this.updatedBy, templateGetContentChannelResponseVersionsInnerTemplatesInner.updatedBy) &&
        Objects.equals(this.approvalCycle, templateGetContentChannelResponseVersionsInnerTemplatesInner.approvalCycle) &&
        Objects.equals(this.isApprovalNeeded, templateGetContentChannelResponseVersionsInnerTemplatesInner.isApprovalNeeded) &&
        Objects.equals(this.isClonedFromLastVersion, templateGetContentChannelResponseVersionsInnerTemplatesInner.isClonedFromLastVersion)&&
        Objects.equals(this.additionalProperties, templateGetContentChannelResponseVersionsInnerTemplatesInner.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, language, isEnabled, approvalStatus, content, createdAt, updatedAt, updatedBy, approvalCycle, isApprovalNeeded, isClonedFromLastVersion, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateGetContentChannelResponseVersionsInnerTemplatesInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    approvalStatus: ").append(toIndentedString(approvalStatus)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    approvalCycle: ").append(toIndentedString(approvalCycle)).append("\n");
    sb.append("    isApprovalNeeded: ").append(toIndentedString(isApprovalNeeded)).append("\n");
    sb.append("    isClonedFromLastVersion: ").append(toIndentedString(isClonedFromLastVersion)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("language");
    openapiFields.add("is_enabled");
    openapiFields.add("approval_status");
    openapiFields.add("content");
    openapiFields.add("created_at");
    openapiFields.add("updated_at");
    openapiFields.add("updated_by");
    openapiFields.add("approval_cycle");
    openapiFields.add("is_approval_needed");
    openapiFields.add("is_cloned_from_last_version");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TemplateGetContentChannelResponseVersionsInnerTemplatesInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TemplateGetContentChannelResponseVersionsInnerTemplatesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateGetContentChannelResponseVersionsInnerTemplatesInner is not found in the empty JSON string", TemplateGetContentChannelResponseVersionsInnerTemplatesInner.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `language`
      if (jsonObj.get("language") != null && !jsonObj.get("language").isJsonNull()) {
        TemplateGetContentChannelResponseVersionsInnerTemplatesInnerLanguage.validateJsonObject(jsonObj.getAsJsonObject("language"));
      }
      if ((jsonObj.get("approval_status") != null && !jsonObj.get("approval_status").isJsonNull()) && !jsonObj.get("approval_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `approval_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("approval_status").toString()));
      }
      // validate the optional field `content`
      if (jsonObj.get("content") != null && !jsonObj.get("content").isJsonNull()) {
        TemplateGetContentChannelResponseVersionsInnerTemplatesInnerContent.validateJsonObject(jsonObj.getAsJsonObject("content"));
      }
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("updated_at") != null && !jsonObj.get("updated_at").isJsonNull()) && !jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
      // validate the optional field `updated_by`
      if (jsonObj.get("updated_by") != null && !jsonObj.get("updated_by").isJsonNull()) {
        TemplateGetContentChannelResponseVersionsInnerTemplatesInnerUpdatedBy.validateJsonObject(jsonObj.getAsJsonObject("updated_by"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateGetContentChannelResponseVersionsInnerTemplatesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateGetContentChannelResponseVersionsInnerTemplatesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateGetContentChannelResponseVersionsInnerTemplatesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateGetContentChannelResponseVersionsInnerTemplatesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateGetContentChannelResponseVersionsInnerTemplatesInner>() {
           @Override
           public void write(JsonWriter out, TemplateGetContentChannelResponseVersionsInnerTemplatesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateGetContentChannelResponseVersionsInnerTemplatesInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TemplateGetContentChannelResponseVersionsInnerTemplatesInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TemplateGetContentChannelResponseVersionsInnerTemplatesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TemplateGetContentChannelResponseVersionsInnerTemplatesInner
  * @throws IOException if the JSON string is invalid with respect to TemplateGetContentChannelResponseVersionsInnerTemplatesInner
  */
  public static TemplateGetContentChannelResponseVersionsInnerTemplatesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateGetContentChannelResponseVersionsInnerTemplatesInner.class);
  }

 /**
  * Convert an instance of TemplateGetContentChannelResponseVersionsInnerTemplatesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

